"""ingredient name_norm

Revision ID: 5890b67b005d
Revises: fbd245535748
Create Date: 2025-12-13 20:19:26.448278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5890b67b005d'
down_revision = 'fbd245535748'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("name_norm", sa.String(length=200), nullable=False, server_default="")
        )

    # заполняем name_norm из name (на SQLite lower() для кириллицы может быть не идеален,
    # но это нужно только для существующих строк; новые мы будем заполнять в Python)
    op.execute("UPDATE ingredients SET name_norm = lower(name) WHERE name_norm = ''")

    # можно убрать server_default (не обязательно)
    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.alter_column("name_norm", server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredients_name_norm'))
        batch_op.drop_column('name_norm')

    # ### end Alembic commands ###
